In [17]:
import pandas as pd
import time
import os
import numpy as np
from datetime import date
import datetime
import matplotlib as mp

In [52]:
df_today=pd.read_excel('SKU_Analysis.xlsx','ITC_CL_SalesWithGradeInfo')
try:
    df_yesterday=pd.read_excel('SKU_Analysis.xlsx','Total Sales')
except:
    df_yesterday;
if df_yesterday.empty:
    ;

AttributeError: 'str' object has no attribute 'empty'

In [3]:
df_s1=df[['Invoice Date','Sales Ledger','SKU','Qty(Kgs)']]

In [4]:
df_s1

     Invoice Date Sales Ledger                              SKU  Qty(Kgs)
0      2020-07-18        Sales                           Carrot     48.40
1      2020-07-18        Sales                             Mint      4.80
2      2020-07-18        Sales                      Cauliflower     24.10
3      2020-07-18        Sales                  Iceberg Lettuce      3.30
4      2020-07-18        Sales                 Zucchini - Green      5.60
5      2020-07-18        Sales                     Spring Onion      3.60
6      2020-07-18        Sales                Zucchini - Yellow      5.60
7      2020-07-18        Sales              Leafy Green Lettuce      3.60
8      2020-07-18        Sales                    Cherry Tomato      3.00
9      2020-07-18        Sales         Rocket (Aragula) Lettuce      2.20
10     2020-07-18        Sales  Leafy Red (Lolla Rossa) Lettuce      1.00
11     2020-07-18        Sales                           Celery      1.60
12     2020-07-18        Sales                 English Cucumber     24.60
13     2020-07-18        Sales                 Capsicum - Green     30.00
14     2020-07-18        Sales                          Spinach     23.20
15     2020-07-18        Sales                        Coriander      9.10
16     2020-07-18        Sales                    Haricot Beans     10.70
17     2020-07-18        Sales             Color Capsicum - Red      8.30
18     2020-07-18        Sales          Color Capsicum - Yellow      8.30
19     2020-07-18        Sales                      Papaya (Kg)      2.80
20     2020-07-18        Sales                  Brinjal Bhartha      1.90
21     2020-07-18        Sales                      Dill Leaves      0.90
22     2020-07-18        Sales                         Beetroot      2.10
23     2020-07-18        Sales                           Celery      5.00
24     2020-07-18        Sales                         Broccoli      7.00
25     2020-07-18        Sales             Color Capsicum - Red      5.00
26     2020-07-18        Sales          Color Capsicum - Yellow      5.00
27     2020-07-18        Sales              Leafy Green Lettuce      2.00
28     2020-07-18        Sales                 English Cucumber      5.00
29     2020-07-18        Sales                      Red Cabbage      1.00
...           ...          ...                              ...       ...
1959   2020-07-18        Sales              Green Amarantus(GT)      2.40
1960   2020-07-18        Sales                     Green Chilly      2.50
1961   2020-07-18        Sales                    Haricot Beans     12.75
1962   2020-07-18        Sales                  Iceberg Lettuce      1.00
1963   2020-07-18        Sales                    Italian Basil      1.10
1964   2020-07-18        Sales                            Lemon      4.90
1965   2020-07-18        Sales                       Lemongrass      1.50
1966   2020-07-18        Sales                     Mango Neelam     27.00
1967   2020-07-18        Sales                        Methi(GT)      7.80
1968   2020-07-18        Sales                        Mint (GT)      2.00
1969   2020-07-18        Sales                        Muskmelon     16.00
1970   2020-07-18        Sales                            Onion     85.00
1971   2020-07-18        Sales                      Papaya (Kg)     37.00
1972   2020-07-18        Sales                          Parsley      0.25
1973   2020-07-18        Sales                           Potato     57.00
1974   2020-07-18        Sales               Red Amarantus.(GT)      1.20
1975   2020-07-18        Sales                      Red Cabbage      1.20
1976   2020-07-18        Sales                       Ridgegourd     18.00
1977   2020-07-18        Sales                   Robusta Banana     14.00
1978   2020-07-18        Sales                  Romaine Lettuce      0.60
1979   2020-07-18        Sales                       Snakegourd      5.50
1980   2020-07-18        Sales                      Spinach(GT)     12.60
1981   2020-07-18        Sales                Spring Onion (GT)      2.80
1982   2020-07-18        Sales           Thai Ginger / Galangal      0.10
1983   2020-07-18        Sales                   Tomato Country     31.00
1984   2020-07-18        Sales                  Tomoto (Hybrid)     33.50
1985   2020-07-18        Sales            Watermelon Kiran (Kg)     17.00
1986   2020-07-18        Sales                   Yalakki Banana     30.00
1987   2020-07-18        Sales                 Zucchini - Green      2.25
1988   2020-07-18        Sales                Zucchini - Yellow      0.50

[1989 rows x 4 columns]

In [30]:
d1=date.today()
#print(d1)
df_x=df_s1[df_s1['Invoice Date'] == d1-datetime.timedelta(days=2)].groupby('SKU').agg(
    {'Qty(Kgs)': [('today_total_qty','sum')]}
)
df_y=df_s1[df_s1['Invoice Date'] == d1-datetime.timedelta(days=3)].groupby('SKU').agg(
    {'Qty(Kgs)': [('yeaterday_total_qty','sum')]}
)

/home/subhankar/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: Comparing Series of datetimes with 'datetime.date'.  Currently, the
'datetime.date' is coerced to a datetime. In the future pandas will
not coerce, and 'the values will not compare equal to the
'datetime.date'. To retain the current behavior, convert the
'datetime.date' to a datetime with 'pd.Timestamp'.
  This is separate from the ipykernel package so we can avoid doing imports until

AttributeError: module 'pandas' has no attribute 'NamedAgg'

In [27]:
df_x

                                Qty(Kgs)
                         today_total_qty
SKU
Apple Royal                        11.00
Asparagus                           0.90
Baby Corn                           4.25
Beetroot                            3.00
Bittergourd                        39.75
Bok Choy                           15.00
Bottlegourd                        78.00
Brinjal Bhartha                    97.00
Brinjal Vari                       78.25
Broccoli                           65.50
Button Mushroom                     7.40
Capsicum - Green                  311.50
Carrot                            337.60
Cauliflower                       234.40
Celery                             22.30
Cherry Tomato                      19.70
Coconut                             4.80
Color Capsicum - Red               34.20
Color Capsicum - Yellow            38.65
Coriander                          17.65
Coriander (GT)                    129.00
Cucumber Hybrid                   456.40
Curry Leaves(GT)                   16.40
Dill Leaves                         0.25
Dill Leaves(GT)                    24.00
English Cucumber                  249.80
Garlic                             92.50
Ginger Whole                      101.75
Green Amarantus(GT)                21.00
Green Chilly                       34.55
...                                  ...
Lemongrass                          0.50
Mango Neelam                       29.00
Methi(GT)                          92.40
Mint                               13.55
Mint (GT)                          28.30
Muskmelon                          19.00
Onion                             241.00
Papaya                              4.00
Papaya (Kg)                        19.80
Parsley                             1.35
Potato                            306.00
Red Amarantus.(GT)                 12.30
Red Cabbage                        52.10
Ridgegourd                        198.00
Robusta Banana                      9.00
Rocket (Aragula) Lettuce            1.70
Romaine Lettuce                     0.15
Snakegourd                         66.00
Spinach                            10.35
Spinach(GT)                       109.20
Spring Onion                        4.50
Spring Onion (GT)                  18.80
Thai Ginger / Galangal              0.30
Tomato Country                   1581.50
Tomoto (Hybrid)                   274.50
Watermelon Kiran                   10.00
Watermelon Kiran (Kg)               9.00
Yalakki Banana                     12.00
Zucchini - Green                   34.30
Zucchini - Yellow                  28.05

[67 rows x 1 columns]

In [28]:
df_y

                                    Qty(Kgs)
                         yeaterday_total_qty
SKU
Apple Royal                            14.00
Asparagus                               1.40
Baby Corn                               2.00
Beetroot                                2.70
Bittergourd                            40.25
Bok Choy                               11.00
Bottlegourd                            90.80
Brinjal Bhartha                        72.80
Brinjal Vari                           32.75
Broccoli                               72.00
Button Mushroom                         8.80
Capsicum - Green                      244.20
Carrot                                302.05
Cauliflower                           338.60
Celery                                 19.50
Cherry Tomato                           5.50
Coconut                                 7.20
Color Capsicum - Red                   34.05
Color Capsicum - Yellow                31.30
Coriander                              19.00
Coriander (GT)                        168.60
Cucumber Hybrid                       313.00
Curry Leaves                            0.30
Curry Leaves(GT)                       18.65
Dill Leaves                             1.00
Dill Leaves(GT)                        23.40
English Cucumber                      193.00
Garlic                                 49.00
Ginger Whole                           70.75
Green Amarantus(GT)                    21.60
...                                      ...
Leeks                                   5.00
Lemon                                  11.50
Lemongrass                              0.25
Mango Neelam                           56.40
Methi(GT)                             103.50
Mint                                   13.10
Mint (GT)                              36.90
Muskmelon                              82.00
Onion                                 365.00
Papaya                                  1.60
Papaya (Kg)                            52.00
Parsley                                 1.70
Potato                                514.00
Red Amarantus.(GT)                     16.50
Red Cabbage                            13.70
Ridgegourd                            156.00
Robusta Banana                         18.00
Rocket (Aragula) Lettuce                1.60
Snakegourd                             41.00
Spinach                                14.20
Spinach(GT)                           109.80
Spring Onion                            9.30
Spring Onion (GT)                      32.40
Tomato Country                        645.50
Tomoto (Hybrid)                       311.50
Watermelon Kiran                       16.00
Watermelon Kiran (Kg)                  12.00
Yalakki Banana                         20.50
Zucchini - Green                       28.70
Zucchini - Yellow                      11.95

[66 rows x 1 columns]

In [38]:
df_sheet1=pd.merge(df_x,df_y,on='SKU',how='outer')
df_sheet1.columns = df_sheet1.columns.get_level_values(1)
df_sheet1=df_sheet1.fillna(0)
df_sheet1['% Growth']=(((df_sheet1['today_total_qty']-df_sheet1['yeaterday_total_qty'])/df_sheet1['yeaterday_total_qty'])*100).round(2)

In [39]:
df_sheet1

                          today_total_qty  yeaterday_total_qty  % Growth
SKU
Apple Royal                         11.00                14.00    -21.43
Asparagus                            0.90                 1.40    -35.71
Baby Corn                            4.25                 2.00    112.50
Beetroot                             3.00                 2.70     11.11
Bittergourd                         39.75                40.25     -1.24
Bok Choy                            15.00                11.00     36.36
Bottlegourd                         78.00                90.80    -14.10
Brinjal Bhartha                     97.00                72.80     33.24
Brinjal Vari                        78.25                32.75    138.93
Broccoli                            65.50                72.00     -9.03
Button Mushroom                      7.40                 8.80    -15.91
Capsicum - Green                   311.50               244.20     27.56
Carrot                             337.60               302.05     11.77
Cauliflower                        234.40               338.60    -30.77
Celery                              22.30                19.50     14.36
Cherry Tomato                       19.70                 5.50    258.18
Coconut                              4.80                 7.20    -33.33
Color Capsicum - Red                34.20                34.05      0.44
Color Capsicum - Yellow             38.65                31.30     23.48
Coriander                           17.65                19.00     -7.11
Coriander (GT)                     129.00               168.60    -23.49
Cucumber Hybrid                    456.40               313.00     45.81
Curry Leaves(GT)                    16.40                18.65    -12.06
Dill Leaves                          0.25                 1.00    -75.00
Dill Leaves(GT)                     24.00                23.40      2.56
English Cucumber                   249.80               193.00     29.43
Garlic                              92.50                49.00     88.78
Ginger Whole                       101.75                70.75     43.82
Green Amarantus(GT)                 21.00                21.60     -2.78
Green Chilly                        34.55                23.40     47.65
...                                   ...                  ...       ...
Mango Neelam                        29.00                56.40    -48.58
Methi(GT)                           92.40               103.50    -10.72
Mint                                13.55                13.10      3.44
Mint (GT)                           28.30                36.90    -23.31
Muskmelon                           19.00                82.00    -76.83
Onion                              241.00               365.00    -33.97
Papaya                               4.00                 1.60    150.00
Papaya (Kg)                         19.80                52.00    -61.92
Parsley                              1.35                 1.70    -20.59
Potato                             306.00               514.00    -40.47
Red Amarantus.(GT)                  12.30                16.50    -25.45
Red Cabbage                         52.10                13.70    280.29
Ridgegourd                         198.00               156.00     26.92
Robusta Banana                       9.00                18.00    -50.00
Rocket (Aragula) Lettuce             1.70                 1.60      6.25
Romaine Lettuce                      0.15                 0.00       inf
Snakegourd                          66.00                41.00     60.98
Spinach                             10.35                14.20    -27.11
Spinach(GT)                        109.20               109.80     -0.55
Spring Onion                         4.50                 9.30    -51.61
Spring Onion (GT)                   18.80                32.40    -41.98
Thai Ginger / Galangal               0.30                 0.00       inf
Tomato Country                    1581.50               645.50    145.00
Tomoto (Hybrid)                    274.50               311.50    -11.88
Watermelon Kiran                    10.00                16.00    -37.50
Watermelon Kiran (Kg)                9.00                12.00    -25.00
Yalakki Banana                      12.00                20.50    -41.46
Zucchini - Green                    34.30                28.70     19.51
Zucchini - Yellow                   28.05                11.95    134.73
Curry Leaves                         0.00                 0.30   -100.00

[68 rows x 3 columns]

In [47]:
df_MTS=df[df['Invoice Date'].dt.month==date.today().month]
df_MTS

,Invoice Number,Invoice Date,Customer Name,Main Customer Group,Customer Group,Sales Ledger,SKU,Grade Type,Qty,Rate,Amount,Sales Ret Qty,Sales Ret Rate,Sales Ret Amount,Qty(Kgs),Net Amount,Channel,Loc
0,BLR/20-21/9405,2020-07-18,BLR/20-21/9406,2020-07-19 00:00:00,BLR/20-21/9407,2020-07-20 00:00:00,BLR/20-21/9408,2020-07-21 00:00:00,BLR/20-21/9409,2020-07-22 00:00:00,BLR/20-21/9410,2020-07-23 00:00:00,BLR/20-21/9411,2020-07-24 00:00:00,BLR/20-21/9412,2020-07-25 00:00:00,BLR/20-21/9413,2020-07-26 00:00:00
1,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Mint,NaN,4.8,60,288,NaN,NaN,NaN,4.8,288,HORECA,Cure Food
2,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Cauliflower,NaN,24.1,35,843.5,NaN,NaN,NaN,24.1,843.5,HORECA,Cure Food
3,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Iceberg Lettuce,NaN,3.3,65,214.5,NaN,NaN,NaN,3.3,214.5,HORECA,Cure Food
4,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Zucchini - Green,NaN,5.6,60,336,NaN,NaN,NaN,5.6,336,HORECA,Cure Food
5,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Spring Onion,NaN,3.6,55,198,NaN,NaN,NaN,3.6,198,HORECA,Cure Food
6,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Zucchini - Yellow,NaN,5.6,60,336,NaN,NaN,NaN,5.6,336,HORECA,Cure Food
7,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Leafy Green Lettuce,NaN,3.6,65,234,NaN,NaN,NaN,3.6,234,HORECA,Cure Food
8,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Cherry Tomato,NaN,3,70,210,NaN,NaN,NaN,3,210,HORECA,Cure Food
9,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Rocket (Aragula) Lettuce,NaN,2.2,90,198,NaN,NaN,NaN,2.2,198,HORECA,Cure Food
10,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Leafy Red (Lolla Rossa) Lettuce,NaN,1,65,65,NaN,NaN,NaN,1,65,HORECA,Cure Food
11,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Celery,NaN,1.6,100,160,NaN,NaN,NaN,1.6,160,HORECA,Cure Food
12,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,English Cucumber,NaN,24.6,30,738,NaN,NaN,NaN,24.6,738,HORECA,Cure Food
13,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Capsicum - Green,NaN,30,35,1050,NaN,NaN,NaN,30,1050,HORECA,Cure Food
14,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Spinach,NaN,23.2,50,1160,NaN,NaN,NaN,23.2,1160,HORECA,Cure Food
15,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Coriander,NaN,9.1,55,500.5,NaN,NaN,NaN,9.1,500.5,HORECA,Cure Food
16,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Haricot Beans,NaN,10.7,70,749,NaN,NaN,NaN,10.7,749,HORECA,Cure Food
17,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Color Capsicum - Red,NaN,8.3,60,498,NaN,NaN,NaN,8.3,498,HORECA,Cure Food
18,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Color Capsicum - Yellow,NaN,8.3,60,498,NaN,NaN,NaN,8.3,498,HORECA,Cure Food
19,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Papaya (Kg),NaN,2.8,40,112,NaN,NaN,NaN,2.8,112,HORECA,Cure Food
20,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Brinjal Bhartha,NaN,1.9,36,68.4,NaN,NaN,NaN,1.9,68.4,HORECA,Cure Food
21,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Dill Leaves,NaN,0.9,55,49.5,NaN,NaN,NaN,0.9,49.5,HORECA,Cure Food
22,BLR/20-21/9405,2020-07-18,Curefoods Private Limited (Whitefield),NaN,Curefoods Private Limited,Sales,Beetroot,NaN,2.1,30,63,NaN,NaN,NaN,2.1,63,HORECA,Cure Food
23,BLR/20-21/9406,2020-07-18,"Nature's Basket LTD, CMH Road",NaN,Nature's Basket LTD,Sales,Celery,NaN,5,77,385,NaN,NaN,NaN,5,385,Modern Retailer,GNB
24,BLR/20-21/9406,2020-07-18,"Nature's Basket LTD, CMH Road",NaN,Nature's Basket LTD,Sales,Broccoli,Grade A,7,142,994,NaN,NaN,NaN,7,994,Modern Retailer,GNB
25,BLR/20-21/9406,2020-07-18,"Nature's Basket LTD, CMH Road",NaN,Nature's Basket LTD,Sales,Color Capsicum - Red,NaN,5,112,560,NaN,NaN,NaN,5,560,Modern Retailer,GNB
26,BLR/20-21/9406,2020-07-18,"Nature's Basket LTD, CMH Road",NaN,Nature's Basket LTD,Sales,Color Capsicum - Yellow,NaN,5,112,560,NaN,NaN,NaN,5,560,Modern Retailer,GNB
27,BLR/20-21/9406,2020-07-18,"Nature's Basket LTD, CMH Road",NaN,Nature's Basket LTD,Sales,Leafy Green Lettuce,NaN,2,87,174,NaN,NaN,NaN,2,174,Modern Retailer,GNB
28,BLR/20-21/9406,2020-07-18,"Nature's Basket LTD, CMH Road",NaN,Nature's Basket LTD,Sales,English Cucumber,NaN,5,42,210,NaN,NaN,NaN,5,210,Modern Retailer,GNB
29,BLR/20-21/9407,2020-07-18,Nature's Basket Ltd Kamanahalli,NaN,Nature's Basket LTD,Sales,Red Cabbage,NaN,1,67,67,NaN,NaN,NaN,1,67,Modern Retailer,GNB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1959,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Green Amarantus(GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.4,96,APT/D2C,APT/D2C
1960,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Green Chilly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,137.5,APT/D2C,APT/D2C
1961,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Haricot Beans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.75,510,APT/D2C,APT/D2C
1962,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Iceberg Lettuce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,120,APT/D2C,APT/D2C
1963,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Italian Basil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.1,132,APT/D2C,APT/D2C
1964,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Lemon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.9,343,APT/D2C,APT/D2C
1965,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Lemongrass,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5,135,APT/D2C,APT/D2C
1966,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Mango Neelam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27,2565,APT/D2C,APT/D2C
1967,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Methi(GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.8,468,APT/D2C,APT/D2C
1968,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Mint (GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,140,APT/D2C,APT/D2C
1969,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Muskmelon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,512,APT/D2C,APT/D2C
1970,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Onion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85,1700,APT/D2C,APT/D2C
1971,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Papaya (Kg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,740,APT/D2C,APT/D2C
1972,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Parsley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.25,22.5,APT/D2C,APT/D2C
1973,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Potato,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57,2166,APT/D2C,APT/D2C
1974,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Red Amarantus.(GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.2,48,APT/D2C,APT/D2C
1975,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Red Cabbage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.2,96,APT/D2C,APT/D2C
1976,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Ridgegourd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,900,APT/D2C,APT/D2C
1977,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Robusta Banana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,350,APT/D2C,APT/D2C
1978,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Romaine Lettuce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.6,96,APT/D2C,APT/D2C
1979,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Snakegourd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.5,154,APT/D2C,APT/D2C
1980,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Spinach(GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.6,756,APT/D2C,APT/D2C
1981,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Spring Onion (GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.8,224,APT/D2C,APT/D2C
1982,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Thai Ginger / Galangal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,40,APT/D2C,APT/D2C
1983,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Tomato Country,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31,1607,APT/D2C,APT/D2C
1984,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Tomoto (Hybrid),NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.5,1206,APT/D2C,APT/D2C
1985,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Watermelon Kiran (Kg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,340,APT/D2C,APT/D2C
1986,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Yalakki Banana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,2160,APT/D2C,APT/D2C
1987,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Zucchini - Green,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.25,240,APT/D2C,APT/D2C
1988,APT,2020-07-18,APT/D2C,NaN,APT/D2C,Sales,Zucchini - Yellow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,85,APT/D2C,APT/D2C